Change node remove. Node name is required.
basho-labs/riak-mesos-tools pull request #56
Opened 2016-10-11 10:04 UTC by platon

2016-10-11 10:21 UTC, platon commented
Example of usage: 
riak-mesos node remove riak-default-1 -f
riak-mesos node remove --force riak-default-1

2016-10-11 12:17 UTC, platon commented
Example of usage: 
riak-mesos node aae-status riak-default-1

2016-10-11 12:20 UTC, platon commented
Example of usage: 
riak-mesos node status riak-default-1

2016-10-11 12:52 UTC, platon commented
Example of usage: 
riak-mesos node ringready riak-default-1

2016-10-11 12:55 UTC, platon commented
Example of usage:
riak-mesos node ringready riak-default-1

2016-10-28 11:52 UTC, platon commented
Example of usage: `cluster create default riak-kv-2.1`

2016-11-18 16:59 UTC, sanmiguel requested changes
OK, I've found a couple of places there emit stacktraces and don't work - I've added the stacktraces I hit to the relevant lines in the tools. Let's try to smooth those out before we merge this

2016-11-18 16:59 UTC, sanmiguel commented on riak_mesos/config.py
> +        resources = self._get_config_value('resources')
Looks like this doesn't work in DCOS:

2016-11-18 16:59 UTC, sanmiguel commented on riak_mesos/config.py
> +        resources = self._get_config_value('resources')
```
 dcos riak config marathon
Traceback (most recent call last):
  File "/Users/sanmiguel/.dcos/subcommands/riak/env/bin/dcos-riak", line 11, in <module>
    load_entry_point('dcos-riak-ts==0.0.1', 'console_scripts', 'dcos-riak')()
  File "/Users/sanmiguel/.dcos/subcommands/riak/env/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/sanmiguel/.dcos/subcommands/riak/env/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/sanmiguel/.dcos/subcommands/riak/env/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/sanmiguel/.dcos/subcommands/riak/env/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/sanmiguel/.dcos/subcommands/riak/env/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/sanmiguel/.dcos/subcommands/riak/env/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/sanmiguel/.dcos/subcommands/riak/env/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/sanmiguel/.dcos/subcommands/riak/env/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/Users/sanmiguel/.dcos/subcommands/riak/env/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/sanmiguel/.dcos/subcommands/riak/env/lib/python2.7/site-packages/riak_mesos/commands/cmd_config.py", line 41, in marathon
    click.echo(ctx.config.framework_marathon_string())
  File "/Users/sanmiguel/.dcos/subcommands/riak/env/lib/python2.7/site-packages/riak_mesos/config.py", line 205, in framework_marathon_string
    return json.dumps(self.framework_marathon_json())
  File "/Users/sanmiguel/.dcos/subcommands/riak/env/lib/python2.7/site-packages/riak_mesos/config.py", line 134, in framework_marathon_json
    mj['fetch'] = self._get_resource_fetch_urls()
  File "/Users/sanmiguel/.dcos/subcommands/riak/env/lib/python2.7/site-packages/riak_mesos/config.py", line 41, in _get_resource_fetch_urls
    resources = self._get_config_value('resources')
  File "/Users/sanmiguel/.dcos/subcommands/riak/env/lib/python2.7/site-packages/riak_mesos/config.py", line 33, in _get_config_value
    value = value[key]
KeyError: 'resources'
```

2016-11-18 16:59 UTC, sanmiguel commented on riak_mesos/config.py
> +        resources = self._get_config_value('resources')
`dcos riak config riak-versions` does work, though...

2016-11-18 16:59 UTC, sanmiguel commented on riak_mesos/config.py
>                  float(conf['RIAK_MESOS_DIRECTOR_CPUS'])
Another missing config key here:

```
dcos riak director install  kv
Traceback (most recent call last):
  File "/Users/sanmiguel/.dcos/subcommands/riak/env/bin/dcos-riak", line 11, in <module>
    load_entry_point('dcos-riak-ts==0.0.1', 'console_scripts', 'dcos-riak')()
  File "/Users/sanmiguel/.dcos/subcommands/riak/env/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/sanmiguel/.dcos/subcommands/riak/env/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/sanmiguel/.dcos/subcommands/riak/env/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/sanmiguel/.dcos/subcommands/riak/env/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/sanmiguel/.dcos/subcommands/riak/env/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/sanmiguel/.dcos/subcommands/riak/env/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/sanmiguel/.dcos/subcommands/riak/env/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/sanmiguel/.dcos/subcommands/riak/env/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/Users/sanmiguel/.dcos/subcommands/riak/env/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/sanmiguel/.dcos/subcommands/riak/env/lib/python2.7/site-packages/riak_mesos/commands/cmd_director.py", line 82, in install
    ctx.config.from_marathon(ctx)
  File "/Users/sanmiguel/.dcos/subcommands/riak/env/lib/python2.7/site-packages/riak_mesos/config.py", line 95, in from_marathon
    float(conf['RIAK_MESOS_DIRECTOR_CPUS'])
KeyError: 'director'
```

2016-11-18 16:59 UTC, sanmiguel commented on riak_mesos/commands/cmd_node.py
>      wait_for_node(ctx, ctx.node)
Another stack trace:

```
 dcos riak node wait-for-service  riak-kv-1
Traceback (most recent call last):
  File "/Users/sanmiguel/.dcos/subcommands/riak/env/bin/dcos-riak", line 11, in <module>
    load_entry_point('dcos-riak-ts==0.0.1', 'console_scripts', 'dcos-riak')()
  File "/Users/sanmiguel/.dcos/subcommands/riak/env/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/sanmiguel/.dcos/subcommands/riak/env/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/sanmiguel/.dcos/subcommands/riak/env/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/sanmiguel/.dcos/subcommands/riak/env/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/sanmiguel/.dcos/subcommands/riak/env/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/sanmiguel/.dcos/subcommands/riak/env/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/sanmiguel/.dcos/subcommands/riak/env/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/sanmiguel/.dcos/subcommands/riak/env/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/Users/sanmiguel/.dcos/subcommands/riak/env/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/sanmiguel/.dcos/subcommands/riak/env/lib/python2.7/site-packages/riak_mesos/commands/cmd_node.py", line 40, in wait_for_service
    wait_for_node(ctx, ctx.node)
  File "/Users/sanmiguel/.dcos/subcommands/riak/env/lib/python2.7/site-packages/riak_mesos/util.py", line 31, in wait_for_node
    node_data = node_info(ctx, node)
  File "/Users/sanmiguel/.dcos/subcommands/riak/env/lib/python2.7/site-packages/riak_mesos/util.py", line 49, in node_info
    mesos_dns_cluster = fw + '-' + cluster + '.' + fw + '.mesos'
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

2016-11-22 13:39 UTC, sanmiguel approved these changes

2016-11-22 13:44 UTC, merged